import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

// eslint-config-next 16 ships native flat configs, so they are spread in directly. The FlatCompat
// bridge (@eslint/eslintrc) that translated the old `extends` strings is gone with it: on version 16
// it crashed ("Converting circular structure to JSON"), and ESLint 10 has no eslintrc support at all.
export default defineConfig([
  ...nextVitals,
  ...nextTs,
  // `next-env.d.ts` is GENERATED by Next on every build and its triple-slash references are
  // required — it is the file that teaches TypeScript about Next's own types. Linting a file the
  // framework rewrites is a rule nobody can satisfy.
  globalIgnores([".next/**", "node_modules/**", "prisma/generated/**", "public/**", "next-env.d.ts"]),
  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" }
      ],
      "@typescript-eslint/no-explicit-any": "warn",
      // next/image is mandatory for anything coming out of the media library — the derivative
      // pipeline and the CDN cache keys both assume the optimiser is in the path.
      "@next/next/no-img-element": "error",
      "react-hooks/exhaustive-deps": "warn",
      // `z` comes from lib/zod.ts, which configures the sentence a reader sees when a schema has not
      // written its own. Imported from "zod" directly, a schema would answer in Zod's developer English
      // in any bundle that did not happen to load lib/zod.ts first. Types and `ZodError` are fine.
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "zod",
              importNames: ["z"],
              message: 'Import `z` from "@/lib/zod" — it carries the application\'s validation messages.'
            }
          ]
        }
      ]
    }
  },
  {
    files: ["lib/zod.ts"],
    rules: { "no-restricted-imports": "off" }
  }
]);
