import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // `next-env.d.ts` is GENERATED by Next on every build and its triple-slash references are
    // required — it is the file that teaches TypeScript about Next's own types. Linting a file the
    // framework rewrites is a rule nobody can satisfy.
    ignores: [".next/**", "node_modules/**", "prisma/generated/**", "public/**", "next-env.d.ts"]
  },
  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" }
      ],
      "@typescript-eslint/no-explicit-any": "warn",
      // next/image is mandatory for anything coming out of the media library — the derivative
      // pipeline and the CDN cache keys both assume the optimiser is in the path.
      "@next/next/no-img-element": "error",
      "react-hooks/exhaustive-deps": "warn"
    }
  }
];

export default eslintConfig;
